export const VIEWPORT_BREAKPOINTS = {
  MOBILE: 480,
  TABLET: 768,
  DESKTOP: 1024,
  WIDE: 1440,
} as const;

export const MOBILE_VIEWPORT = VIEWPORT_BREAKPOINTS.MOBILE;

export const CSS_BREAKPOINTS = {
  MOBILE: `${VIEWPORT_BREAKPOINTS.MOBILE}px`,
  TABLET: `${VIEWPORT_BREAKPOINTS.TABLET}px`,
  DESKTOP: `${VIEWPORT_BREAKPOINTS.DESKTOP}px`,
  WIDE: `${VIEWPORT_BREAKPOINTS.WIDE}px`,
} as const;

export const IMAGE_PADDING_RIGHT_REM = 1; // Right padding for images in rem
